//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Game/Player/Camera Control/Player Camera Controller.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Regicide.Game.Player
{
    public partial class @PlayerCameraController : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerCameraController()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player Camera Controller"",
    ""maps"": [
        {
            ""name"": ""Player Camera Movement"",
            ""id"": ""b0169927-7612-423e-9624-1e775bb79504"",
            ""actions"": [
                {
                    ""name"": ""Direct Move"",
                    ""type"": ""Value"",
                    ""id"": ""cfa83cf1-585e-460c-a912-0dad5d4c05b3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Drag Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d36ebfbc-d6e5-4737-b7d7-996d1094a5fa"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f5f7d6d2-8cf0-4673-b61e-f2bd9d4995f9"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Button"",
                    ""id"": ""98fccfe9-6fa1-4358-aa48-042295af36ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Move Vector"",
                    ""id"": ""4bb576f4-ef4b-490a-af25-b3c8b30bd68e"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Direct Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f490ca81-7f91-400b-a87d-90f833eea26f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard + Mouse"",
                    ""action"": ""Direct Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a52ecd67-8efb-4892-aa5e-8bb6eb6d3abd"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard + Mouse"",
                    ""action"": ""Direct Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e338745c-65e6-4ade-a11d-d732a287a2f2"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard + Mouse"",
                    ""action"": ""Direct Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ebda7749-9b6b-4a1b-a6c0-4342863f0022"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard + Mouse"",
                    ""action"": ""Direct Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""744e0083-8758-4a12-b879-c178d4a49276"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6eb756a1-7531-407f-a77b-7bb7d14670eb"",
                    ""path"": ""<Pointer>/press"",
                    ""interactions"": ""Hold(duration=0.01)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drag Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Rotate Direction"",
                    ""id"": ""e69c1253-583c-4a9c-9c07-2adbfc2ab205"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""a55a4474-58dc-4798-a624-47928501a760"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard + Mouse"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""1da45988-0fde-4290-b970-39a24f178255"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard + Mouse"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard + Mouse"",
            ""bindingGroup"": ""Keyboard + Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Player Camera Movement
            m_PlayerCameraMovement = asset.FindActionMap("Player Camera Movement", throwIfNotFound: true);
            m_PlayerCameraMovement_DirectMove = m_PlayerCameraMovement.FindAction("Direct Move", throwIfNotFound: true);
            m_PlayerCameraMovement_DragMove = m_PlayerCameraMovement.FindAction("Drag Move", throwIfNotFound: true);
            m_PlayerCameraMovement_Zoom = m_PlayerCameraMovement.FindAction("Zoom", throwIfNotFound: true);
            m_PlayerCameraMovement_Rotate = m_PlayerCameraMovement.FindAction("Rotate", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Player Camera Movement
        private readonly InputActionMap m_PlayerCameraMovement;
        private IPlayerCameraMovementActions m_PlayerCameraMovementActionsCallbackInterface;
        private readonly InputAction m_PlayerCameraMovement_DirectMove;
        private readonly InputAction m_PlayerCameraMovement_DragMove;
        private readonly InputAction m_PlayerCameraMovement_Zoom;
        private readonly InputAction m_PlayerCameraMovement_Rotate;
        public struct PlayerCameraMovementActions
        {
            private @PlayerCameraController m_Wrapper;
            public PlayerCameraMovementActions(@PlayerCameraController wrapper) { m_Wrapper = wrapper; }
            public InputAction @DirectMove => m_Wrapper.m_PlayerCameraMovement_DirectMove;
            public InputAction @DragMove => m_Wrapper.m_PlayerCameraMovement_DragMove;
            public InputAction @Zoom => m_Wrapper.m_PlayerCameraMovement_Zoom;
            public InputAction @Rotate => m_Wrapper.m_PlayerCameraMovement_Rotate;
            public InputActionMap Get() { return m_Wrapper.m_PlayerCameraMovement; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerCameraMovementActions set) { return set.Get(); }
            public void SetCallbacks(IPlayerCameraMovementActions instance)
            {
                if (m_Wrapper.m_PlayerCameraMovementActionsCallbackInterface != null)
                {
                    @DirectMove.started -= m_Wrapper.m_PlayerCameraMovementActionsCallbackInterface.OnDirectMove;
                    @DirectMove.performed -= m_Wrapper.m_PlayerCameraMovementActionsCallbackInterface.OnDirectMove;
                    @DirectMove.canceled -= m_Wrapper.m_PlayerCameraMovementActionsCallbackInterface.OnDirectMove;
                    @DragMove.started -= m_Wrapper.m_PlayerCameraMovementActionsCallbackInterface.OnDragMove;
                    @DragMove.performed -= m_Wrapper.m_PlayerCameraMovementActionsCallbackInterface.OnDragMove;
                    @DragMove.canceled -= m_Wrapper.m_PlayerCameraMovementActionsCallbackInterface.OnDragMove;
                    @Zoom.started -= m_Wrapper.m_PlayerCameraMovementActionsCallbackInterface.OnZoom;
                    @Zoom.performed -= m_Wrapper.m_PlayerCameraMovementActionsCallbackInterface.OnZoom;
                    @Zoom.canceled -= m_Wrapper.m_PlayerCameraMovementActionsCallbackInterface.OnZoom;
                    @Rotate.started -= m_Wrapper.m_PlayerCameraMovementActionsCallbackInterface.OnRotate;
                    @Rotate.performed -= m_Wrapper.m_PlayerCameraMovementActionsCallbackInterface.OnRotate;
                    @Rotate.canceled -= m_Wrapper.m_PlayerCameraMovementActionsCallbackInterface.OnRotate;
                }
                m_Wrapper.m_PlayerCameraMovementActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @DirectMove.started += instance.OnDirectMove;
                    @DirectMove.performed += instance.OnDirectMove;
                    @DirectMove.canceled += instance.OnDirectMove;
                    @DragMove.started += instance.OnDragMove;
                    @DragMove.performed += instance.OnDragMove;
                    @DragMove.canceled += instance.OnDragMove;
                    @Zoom.started += instance.OnZoom;
                    @Zoom.performed += instance.OnZoom;
                    @Zoom.canceled += instance.OnZoom;
                    @Rotate.started += instance.OnRotate;
                    @Rotate.performed += instance.OnRotate;
                    @Rotate.canceled += instance.OnRotate;
                }
            }
        }
        public PlayerCameraMovementActions @PlayerCameraMovement => new PlayerCameraMovementActions(this);
        private int m_KeyboardMouseSchemeIndex = -1;
        public InputControlScheme KeyboardMouseScheme
        {
            get
            {
                if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard + Mouse");
                return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
            }
        }
        public interface IPlayerCameraMovementActions
        {
            void OnDirectMove(InputAction.CallbackContext context);
            void OnDragMove(InputAction.CallbackContext context);
            void OnZoom(InputAction.CallbackContext context);
            void OnRotate(InputAction.CallbackContext context);
        }
    }
}
